version: "3.8"
services:
  app:
    image: plamer88/skywars:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - '80:5000'
    depends_on:
      postgres:
        condition: service_healthy
      make_migrations:
        condition: service_completed_successfully
    volumes:
      - ./config.py:/skywars/config.py

  make_migrations:
    image: plamer88/skywars:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
    command: "python3 create_db.py && python3 add_admin.py"
    volumes:
      - ./add_admin.py:/skywars/add_admin.py
      - ./admin.json:/skywars/data/admin.json
      - ./config.py:/skywars/config.py

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready --username=$POSTGRES_USER -d $POSTGRES_DB']
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
