name: skywars copy and deploy
on: [push]
jobs:
  build_image:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{secrets.POSTGRES_DB}}
      DB_PASS: ${{secrets.POSTGRES_PASSWORD}}
      DB_USER: ${{secrets.POSTGRES_USER}}
      DB_HOST: postgres

    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: prepare config.py
        run: |
          mkdir temp          
          cat config.py | envsubst > temp/config.py
          cp temp/config.py config.py
      - name: build image
        run: docker build -t plamer88/skywars:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{secrets.DOCKER_PASS_TOKEN}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: push image
        run: docker push plamer88/skywars:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy_application:
    runs-on: ubuntu-latest
    needs: build_image
    env:
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
    steps:
      - name: clone git repository
        uses: actions/checkout@v2
      - name: prepare files
        run: |
          mkdir temp
          cp skywars.service temp/skywars.service
          cp create_db.py temp/create_db.py
          cp add_admin.py temp/add_admin.py          
          cat docker-compose-ci.yaml | envsubst > temp/docker-compose.yaml
          cat data/admin.json | envsubst > temp/admin.json

      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.APP_HOST}}
          username: ${{secrets.SKYWARS_USERNAME}}
          password: ${{secrets.SKYWARS_SERVER_PASS}}
          source: "temp/docker-compose.yaml,temp/skywars.service,temp/create_db.py,temp/admin.json,temp/add_admin.py"
          target: "/home/skywars"
          strip_components: 1

      - name: run application
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.APP_HOST}}
          username: ${{secrets.SKYWARS_USERNAME}}
          password: ${{secrets.SKYWARS_SERVER_PASS}}
          script: |
            cd /home/skywars
            python3 add_admin.py
            cp skywars.service /etc/systemd/system
            systemctl stop skywars
            systemctl daemon-reload
            systemctl start skywars
            systemctl enable skywars
